### PR TITLE
Revised some names for clarity

### PR DESCRIPTION
**Pull request by bramtayl**
Not a big deal, just some renaming

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
I think this pull request should not have been written.

At best, this kind of name-convention change is a misuse of the core developers' time because it does not change the package's actual functionality.

At worst, this change suggests that you do not care about the objectives of the core developers of this package who did not choose the names you are changing without some careful thought. I do not think you intended to convey the message that you view the core developers as incompetent, but you should be aware that pull requests like this one suggest that you have not thought very carefully about the question, "why did other people decide to use the kind of names that I dislike?"

If you're truly interested in contributing to Julia's development, I think you might have more success asking for a mentor who could tell you what to work on and who could criticize your work on purely technical grounds as you mature into a skilled developer.

As things stand now, you continue to focus almost exclusively on aesthetic issues that will not increase your credibility as a potential contributor. That will make it hard for you to realize your own objectives in the future because other people will not come to view you as a viable ally who they can collaborate effectively with.

**Comment by bramtayl** [comment]
I was just trying to be helpful. I think that clearer names will help future contributors (most notably me) understand the code better. For the record, I absolutely do not think that any developer of this package is incompetent; I'm in awe of the skills of you guys.

**Comment by bramtayl** [comment]
However, if you'd like to mentor me, I would appreciate the help.

**Comment by bramtayl** [comment]
Lol

**Pull request closed without merging**
